#!/usr/bin/env bash

# List the bucket content to here

if [ -z "$1" ]; then
  echo "A bucket name is required."
  exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key
